Describe Async.Later
  Before
    let Later = healthcheck#vital#import('Async.Later')
  End

  Describe .call()
    It registers a task and call it a bit later
      let rs = []
      call Later.call({ -> add(rs, 1) })
      Assert Equals(rs, [])
      sleep 10m
      Assert Equals(rs, [1])
    End

    It calls tasks in FIFO manner
      let rs = []
      call Later.call({ -> add(rs, 1) })
      call Later.call({ -> add(rs, 2) })
      call Later.call({ -> add(rs, 3) })
      Assert Equals(rs, [])
      sleep 10m
      Assert Equals(rs, [1, 2, 3])
    End

    It calls tasks in FIFO manner (nest)
      let rs = []
      call Later.call({ -> add(rs, 1) })
      call Later.call({ -> Later.call({ -> add(rs, 3) }) })
      call Later.call({ -> Later.call({ -> Later.call({ -> add(rs, 5) }) }) })
      call Later.call({ -> Later.call({ -> add(rs, 4) }) })
      call Later.call({ -> add(rs, 2) })
      Assert Equals(rs, [])
      sleep 10m
      Assert Equals(rs, [1, 2, 3, 4, 5])
    End

    It calls task in FIFO manner (block)
      function! s:block(time) abort
        let s = reltime()
        while reltimefloat(reltime(s)) * 1000 < a:time
        endwhile
      endfunction

      let rs = []
      call Later.call({ -> [s:block(30), add(rs, 1)] })
      call Later.call({ -> [s:block(10), add(rs, 2)] })
      call Later.call({ -> [s:block(20), add(rs, 3)] })
      call Later.call({ -> add(rs, 4) })
      sleep 100m
      Assert Equals(rs, [1, 2, 3, 4])
    End

    It echomsg an exception when a task throws an exception
      function! s:throw(message) abort
        throw a:message
      endfunction

      let exception = v:null
      try
        redir => messages
        call Later.call({ -> s:throw('Hello World') })
        sleep 10m
      catch
        let exception = v:exception
      finally
        redir END
      endtry
      Assert Equals(exception, v:null)
      Assert Match(
            \ messages,
            \ '^\nHello World\nfunction .*<SNR>\d\+_throw, line 1',
            \)
    End
  End
End
